FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

CMD ["sh", "-c", "npm run build && cp -r .output /app/output && rm -rf .output .nuxt && echo 'Build complete!'"]
