# Use the official Node.js image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

COPY /package*.json ./

# Install dependencies
RUN npm install

# Expose the Nuxt.js development server port
EXPOSE 3000